name: deploy
on: 
  workflow_run: 
    workflows: ["workflow"]
    types: [completed]
jobs: 
  dev: 
    runs-on: ubuntu-latest
    environment: DEV
    steps: 
    - uses: actions/checkout@v3
    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  stage: 
    runs-on: ubuntu-latest
    environment: Stage
    steps: 
    - uses: actions/checkout@v3
    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
  prod: 
    runs-on: ubuntu-latest
    environment: Prod
    steps: 
    - uses: actions/checkout@v3
    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}